data_path: /home/pervinco/image-classification/datasets
save_path: /home/pervinco/image-classification/runs

seed: 1994
valid_ratio: 0.2
num_workers: 32
save_batch_imgs: True

model_name: efficientnetv2_rw_m.agc_in1k ## resnet, efficientnet_b0, efficientnetv2_rw_m.agc_in1k
epochs: 1000
img_size: 512
batch_size: 32
learning_rate: 0.00001
weight_decay: 0.000001
early_stop_patience: 10